---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("instacart")

instacart = 
  instacart |> 
  as_tibble()
```

Column {data-width=650}
-----------------------------------------------------------------------

### Order hour of day by frozen department aisle

```{r}

instacart |> 
  filter(department %in% ("frozen")) |>
  select(aisle, order_hour_of_day) |> 
  group_by(aisle) |> 
  plot_ly(
  y = ~order_hour_of_day, color = ~aisle, type = "box", colors = "viridis") |> 
  layout(xaxis = list(title = "Aisle"),
         yaxis = list(title = "Order hour of day"))
    
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Instacart reorders per department

```{r}
  instacart |> 
  select(reordered, department) |> 
  filter(reordered == 1) |> 
  group_by(department) |>
  count(reordered) |> 
  ungroup() |> 
  mutate(department = fct_reorder(department, n)) |> 
  plot_ly(
    x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis") |> 
  layout(xaxis = list(title = "reorder"),
         yaxis = list(title = "Number of reorders"))
```


### Number of Instacart orders per snack department aisle by day of the week

```{r}
  instacart |> 
  filter(department %in% ("snacks")) |> 
  select(aisle, order_dow) |> 
  group_by(aisle, order_dow) |> 
  summarize(n = n()) |> 
  plot_ly(
    x=~order_dow, y = ~n, type ="scatter", color = ~aisle, mode = "lines", colors = "viridis") |> 
layout(xaxis = list(title = "Day of the week"), yaxis = list(title = "Number of orders"))
```

